name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
      - uses: actions/checkout@v2
      - name: Create output directory
        run: mkdir bin
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Compile code
        run: javac -encoding UTF-8 -sourcepath src -d bin src/*.java

      - name: Package jar
        run: jar cvfe ${{ github.event.repository.name }}.jar TankGameMain -C bin .

      - name: Upload jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ${{ github.event.repository.name }}.jar

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          timeout: 60s
          retries: 3
          files: |
            ${{ github.event.repository.name }}.jar